export { default as Home } from "./Home";
export { default as DashBoard } from "./DashBoard";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Products } from "./Products";
export { default as SingleProduct } from "./SingleProduct";
export { default as Cart } from "./Cart";
export { default as Contact } from "./Contact";
export { default as About } from "./About";
